### ISSUE TITLE
System variable are not taken into account in Links

### ISSUE THREAD

**Issue by loms0815** [jenkinsci/customizable-header-plugin#148]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1: Set System Variable NEXUS_URL in System
2: Add Link in Appearance with ${NEXUS} as value

### Expected Results

Link works (upper left corner)

### Actual Results

Link /$%7BNEXUS_URL%7D is called.

**Comment by mawinter69** [comment]
This is not script a environment. I don't really see a need for this feature. A system Property is usually set as startup parameter, so it will never change. But then you can also just use CasC and configure the plugin.

**Comment by mawinter69** [comment]
I do not intend to implement this feature
