### ISSUE TITLE
Store a resized copy of the logo image

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/customizable-header-plugin#22]
### What feature do you want to see added?

I'd like the plugin to store a resized copy of the logo image so it can be optimally served and avoid error in case the image used is missing.

Currently the header is hotlinking the logo, resulting in flashing if the image is big (as the image is resized on the fly but briefly displayed at its original size) and unnecessary bandwidth consumption.

<img width="667" alt="image" src="https://github.com/jenkinsci/customizable-header-plugin/assets/91831478/64ab9b4c-6f46-4479-a894-1baf9ccc73b9">

Corresponding config: https://github.com/jenkins-infra/kubernetes-management/blob/2b0cf03ced0d552da2e3fd16e39ebdbd25ba2396/config/jenkins_infra.ci.jenkins.io.yaml#L717-L729

**Comment by mawinter69** [comment]
@lemeurherve Do you still need this or is the change from #49 enough to solve the issue you described here?

**Comment by mawinter69** [comment]
I tried to incorporate thumbnailator, but the results are not so good. The quality of the image is much better when the browser scales it down. Also one thing to consider is that on big monitors when e.g. windows is scaling, then the actual image can be bigger than what we give in the size attributes. The browser is probably much better able to find the right size and resize the image.
Bandwidth is not really a problem I think, the image should be cached by the browser.

**Comment by lemeurherve** [comment]
I think #49 is enough, I haven't managed to reproduce the flickering issue since.

Thanks!
