### ISSUE TITLE
Application navigator button

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkinsci/customizable-header-plugin#25]
### What feature do you want to see added?

I'd like to have a button at the top left corner that I can click to open a menu for navigating to related non-Jenkins Web sites that already have similar buttons.

The list of linked Web sites would be configured by the Jenkins administrator.  Each link would have:

* Icon.  The administrator would typically deploy the image under `userContent`.
* Visible text.
* Target URI.
* A way to control whether the link is shown to unauthenticated users.  Perhaps a whole ACL.

## Prior art in other Web sites

Microsoft Teams has an application navigator button with 3*3 dots:

![Screen shot of Microsoft Teams application navigator button in Microsoft Edge](https://github.com/jenkinsci/customizable-header-plugin/assets/46201428/fbbea95b-5676-4f5b-9b57-18ea545af3ea) ![Screen shot of Microsoft Teams application navigation menu in Microsoft Edge](https://github.com/jenkinsci/customizable-header-plugin/assets/46201428/92e69549-c131-4a7e-afc7-a77ffa5ffcbf)

Atlassian Jira Cloud has an application navigator button with 3*3 squares:

![Screen shot of Atlassian Jira application navigator button in Microsoft Edge](https://github.com/jenkinsci/customizable-header-plugin/assets/46201428/b1793bec-800c-4dad-93f7-418fd998e8c4) ![Screen shot of Atlassian Jira application navigation menu in Microsoft Edge](https://github.com/jenkinsci/customizable-header-plugin/assets/46201428/67f573c5-c5fd-496d-9169-a4f3f3ce0c5c)

## Alternative: HTML in title

It is already possible to set up something similar by using this Customizable Header plugin and adding HTML to the title field and custom CSS to show the menu on `:hover`.  The result looks nice but is not entirely satisfactory:

- `:hover` makes the menu easy to open accidentally for mouse users.
- `:hover` without a tab stop makes the menu unreachable for blind users.
- The title is at the right side of the Jenkins logo, so it's not consistent with non-Jenkins web sites having the application navigator button in the corner.
- Jenkins strips `class` attributes from the HTML, which requires some contortions in the custom CSS.
- The Web browser temporarily renders the title wrong, when it has loaded the HTML but not yet the custom CSS.
- Unauthenticated users would see the same links.

![image](https://github.com/jenkinsci/customizable-header-plugin/assets/46201428/d7b9a0eb-5fae-4d63-80cf-d6258f465c62)

## Alternative: Sidebar Link plugin

The [Sidebar Link](https://plugins.jenkins.io/sidebar-link/) plugin lets a Jenkins administrator add links to other websites in the sidebar of the main Jenkins dashboard.  However:

- The sidebar mainly consists of links to pages within Jenkins.  I'd like to separate the application navigation from these.
- The content of the sidebar depends on which page is open within Jenkins.  I'd like the application navigation to be the same on all pages.

**Comment by mawinter69** [comment]
If you want to combine this new feature with the things here you need to implement it here.

**Comment by mawinter69** [comment]
@KalleOlaviNiemitalo I'm working on this, have something running except for the ACL stuff

**Comment by mawinter69** [comment]
Should be fixed with 40.v2e0e4f17e70c
