### ISSUE TITLE
Open application links in the same tab

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkinsci/customizable-header-plugin#36]
### What feature do you want to see added?

Currently, the application links (<https://github.com/jenkinsci/customizable-header-plugin/issues/25>) have `target="_blank"` so they open in a new tab of the Web browser.  I'd like a way to open them in the current tab by default, but allow Ctrl+click or middle-click to open in a new tab.

This could be a global setting or a per-user setting.  I don't think it should be configurable for each application link; that would just confuse users.

According to <https://github.com/jenkinsci/customizable-header-plugin/pull/31#issuecomment-1763450800>, Microsoft and Jira open application links in new tabs.  I can confirm that for Microsoft, but not for Jira.  Jira Cloud <https://jira.atlassian.com/secure/Dashboard.jspa> opens application links in the current tab, and so does Jira Server, even if my user profile is configured with "External links: Open in new tab".

**Comment by mawinter69** [comment]
Links now always open in the same tab. I didn't make it configurable. So with Ctrl+click or middle-click links should open in new window
