### ISSUE TITLE
Unable to configure Customizable Header in system configure

### ISSUE THREAD

**Issue by gadgetwhiz** [jenkinsci/customizable-header-plugin#56]
### Jenkins and plugins versions report

After install of customizable-header plugin, it is not possible to configure the customizable header in system config. 

The plugin has been successfully installed and configured on several systems (5 so far).

However, we have 2 systems that do not display customizable header configuration fields after plugin install:

Controller 1:
OS: Red Hat Enterprise Linux 9.2
Jenkins version (LTS):  2.426.1-1.1                                                                              @
customizable-header version: 61.v9c97c69b_7ee3

Controller 2: 
OS: Red Hat Enterprise Linux 9.2
Jenkins version (Weekly): 2.430 
customizable-header version: 61.v9c97c69b_7ee3

A jenkins log recorder was configured for 'io.jenkins.plugins.customizable_header' with both all and finest levels but no log output was observed in the recorder. 

No log statements for customizable_header observed in journalctl.

Any diagnostic tips are appreciated.

### What Operating System are you using (both controller, and any agents involved in the problem)?

 Red Hat Enterprise Linux 9.2

### Reproduction steps

- Install plugin customizable-header.
- Reload, service restart, host reboot all unsuccessful.

### Expected Results

Able to configure Customizable header at http://JENKINS_CONTROLLER_URL/manage/configure link.

### Actual Results

Unable to configure Customizable Header via http://JENKINS_CONTROLLER_URL/manage/configure link
/var/lib/jenkins/io.jenkins.plugins.customizable_header.CustomHeaderConfiguration.xml not present

### Anything else?

Workaround:
If I manually copy/edit the io.jenkins.plugins.customizable_header.CustomHeaderConfiguration.xml from another system and restart the Jenkins service, the banner is properly displayed.

### Are you interested in contributing a fix?

I can assist in debugging if provided some guidance.

**Comment by mawinter69** [comment]
With Jenkins 2.426.1 the plugin is configured in the Appearance category. This is an own link under "Manage Jenkins"
http://JENKINS_CONTROLLER_URL/manage/appearance

**Comment by gadgetwhiz** [comment]
Alright, I missed a peek at the release notes that mentioned the change and was relying on my prior experience. 

Perhaps the documentation can be updated with guidance to _Navigate to Manage Jenkins > Appearance to edit the Customizable Header_
