### ISSUE TITLE
Add option to open application links in a new tab

### ISSUE THREAD

**Issue by kevin-uslu** [jenkinsci/customizable-header-plugin#76]
### What feature do you want to see added?

It would be nice to have a checkbox for the application link to indicate whether it should open in a new tab or not.

**Comment by kevin-uslu** [comment]
I think it would be ideal if it was per link so I can set up external links to open up in new tab and Jenkins links (/script, /safeRestart, /restart...etc.) to open up in the same tab.
I do know Ctrl+Click and Mouse middle button shortcuts but some of my users don't.
The possible confusion could be mitigated by adding an icon to right side of the link indicating its type/behavior.

Or maybe if this is too much work, a global option to set the default behavior for all tabs would be appreciated.

**Comment by mawinter69** [comment]
consider that the links are available to everyone, so if you add a link to `/script` any non admin user would get a 404

**Comment by kevin-uslu** [comment]
Fair enough.

I guess I would mostly advise my users to use Favorite function for Jenkins URLs.
ACL issues aside, my expectation for external links is for them to be opened in a new tab.
It would be nice to have the behavior configurable one way or another (global/per link).
